# Dataset de Airbnb NYC

In [1]:
import pandas as pd
import numpy as np

### La siguiente celda  guarda cada hoja del archivo excel en un dataframe

In [12]:
df1 = pd.read_excel("/Users/rociocuestapedraz/Desktop/PYTHON bootcamp DS/datasets/Airbnb_NYC.xlsx",sheet_name = "NYC1")
df2 = pd.read_excel("/Users/rociocuestapedraz/Desktop/PYTHON bootcamp DS/datasets/Airbnb_NYC.xlsx",sheet_name = "NYC2")

In [17]:
df1.head()

id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787   
1  2595                             Skylit Midtown Castle     2845   
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632   
3  3831                   Cozy Entire Floor of Brownstone     4869   
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192   

     host_name  municipio        barrio  latitude  longitude        room_type  
0         John   Brooklyn    Kensington  40.64749  -73.97237     Private room  
1     Jennifer  Manhattan       Midtown  40.75362  -73.98377  Entire home/apt  
2    Elisabeth  Manhattan        Harlem  40.80902  -73.94190     Private room  
3  LisaRoxanne   Brooklyn  Clinton Hill  40.68514  -73.95976  Entire home/apt  
4        Laura  Manhattan   East Harlem  40.79851  -73.94399  Entire home/apt

In [14]:
df2.head()

id  price  minimum_nights  number_of_reviews last_review  \
0  2539.0  149.0             1.0                9.0  2018-10-19   
1  2595.0  225.0             1.0               45.0  2019-05-21   
2  3647.0  150.0             3.0                0.0         NaT   
3  3831.0   89.0             1.0              270.0  2019-07-05   
4  5022.0   80.0            10.0                9.0  2018-11-19   

   reviews_per_month  calculated_host_listings_count  availability_365  
0               0.21                             6.0             365.0  
1               0.38                             2.0             355.0  
2                NaN                             1.0             365.0  
3               4.64                             1.0             194.0  
4               0.10                             1.0               0.0

**1. Unir los dos dataframe anteriores por la columna "id"**

In [18]:
df=pd.merge(df1,df2,on="id")
df.head()

id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787   
1  2595                             Skylit Midtown Castle     2845   
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632   
3  3831                   Cozy Entire Floor of Brownstone     4869   
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192   

     host_name  municipio        barrio  latitude  longitude        room_type  \
0         John   Brooklyn    Kensington  40.64749  -73.97237     Private room   
1     Jennifer  Manhattan       Midtown  40.75362  -73.98377  Entire home/apt   
2    Elisabeth  Manhattan        Harlem  40.80902  -73.94190     Private room   
3  LisaRoxanne   Brooklyn  Clinton Hill  40.68514  -73.95976  Entire home/apt   
4        Laura  Manhattan   East Harlem  40.79851  -73.94399  Entire home/apt   

   price  minimum_nights  number_of_reviews last_review  reviews_per_month  \
0  149.0             1.0                9.0  2018-10-19               0.21   
1  225.0             1.0               45.0  2019-05-21               0.38   
2  150.0             3.0                0.0         NaT                NaN   
3   89.0             1.0              270.0  2019-07-05               4.64   
4   80.0            10.0                9.0  2018-11-19               0.10   

   calculated_host_listings_count  availability_365  
0                             6.0             365.0  
1                             2.0             355.0  
2                             1.0             365.0  
3                             1.0             194.0  
4                             1.0               0.0

**2.	¿Si quiero hospedarme en Manhattan una sola noche y para elegir el Airbnb me guio por el que tenga el mayor número de *review* donde me debería de hospedar?**

In [62]:
df2=df[df["municipio"]=="Manhattan"]
df2[(df2["minimum_nights"]==1)&(df2["number_of_reviews"]==df2["number_of_reviews"].max())&(df2["minimum_nights"]==1)]

id                        name  host_id host_name  municipio  \
2031  903972  Great Bedroom in Manhattan  4734398        Jj  Manhattan   

      barrio  latitude  longitude     room_type  price  minimum_nights  \
2031  Harlem  40.82085  -73.94025  Private room   49.0             1.0   

      number_of_reviews last_review  reviews_per_month  \
2031              607.0  2019-06-21               7.75   

      calculated_host_listings_count  availability_365  \
2031                             3.0             293.0   

                                 Formula  
2031  <function <lambda> at 0x11d59ad40>

**3.	 Busco un Airbnb en el municipio donde el precio promedio de alquiler sea el más bajo y la cantidad de *review* por mes sea el mayor. ¿Cuáles son las 3 habitaciones que mejor se adaptan a estos criterios?**

In [30]:
df["price"]=df["price"].replace(0,np.nan)
df2=df[(df["price"]==df["price"].min())]
df2.sort_values("reviews_per_month").head(3)

id                                               name    host_id  \
22287  17979764                                            Jen Apt   84497333   
24100  19415314  Girls only, cozy room one block from Times Square   47336995   
31066  24114389    Very Spacious bedroom, steps from CENTRAL PARK.  180661875   

      host_name  municipio           barrio  latitude  longitude  \
22287  Jennifer  Manhattan             SoHo  40.72237  -73.99817   
24100     Mario  Manhattan   Hell's Kitchen  40.75812  -73.98935   
31066     Salim  Manhattan  Upper West Side  40.76844  -73.98333   

          room_type  price  minimum_nights  number_of_reviews last_review  \
22287  Private room   10.0             5.0                2.0  2017-04-15   
24100   Shared room   10.0             1.0                2.0  2017-06-24   
31066  Private room   10.0             1.0                2.0  2018-04-23   

       reviews_per_month  calculated_host_listings_count  availability_365  
22287               0.07                             1.0               0.0  
24100               0.08                             1.0               0.0  
31066               0.13                             1.0               0.0

**4.	Quiero rentar un Airbnb completo por un total de 200 días, en Brooklyn o Manhattan; no quiero pagar más de 150 dólares por noche, ¿Cuáles son las 5 opciones más economicas que me ofrece Airbnb?**

In [61]:
df[(df["municipio"].isin(["Manhattan","Brooklyn"]))&(df["price"]<150)&(df["room_type"]=="Entire home/apt")].sort_values("price").head(5)


id                                               name    host_id  \
2860    1620248      Large furnished 2 bedrooms- - 30 days Minimum    2196224   
32810  25839759  Gigantic Sunny Room in Park Slope-Private Back...  167570251   
35601  28270998       Charming, bright and brand new Bed-Stuy home     647528   
23256  18835820             Quiet, Cozy UES Studio Near the Subway   52777892   
27972  21869057      Spacious 2-bedroom Apt in Heart of Greenpoint   11967922   

               host_name  municipio              barrio  latitude  longitude  \
2860               Sally  Manhattan        East Village  40.73051  -73.98140   
32810             Rachel   Brooklyn         Sunset Park  40.66242  -73.99464   
35601           Caterina   Brooklyn  Bedford-Stuyvesant  40.69508  -73.95164   
23256                Amy  Manhattan     Upper East Side  40.76844  -73.95341   
27972  Vishanti & Jeremy   Brooklyn          Greenpoint  40.72421  -73.95364   

             room_type  price  minimum_nights  number_of_reviews last_review  \
2860   Entire home/apt   10.0            30.0                0.0         NaT   
32810  Entire home/apt   10.0             1.0               14.0  2018-10-28   
35601  Entire home/apt   10.0             3.0                5.0  2019-07-02   
23256  Entire home/apt   10.0             3.0               10.0  2018-10-22   
27972  Entire home/apt   10.0             1.0               93.0  2019-07-01   

       reviews_per_month  calculated_host_listings_count  availability_365  \
2860                 NaN                             4.0             137.0   
32810               1.06                             1.0               4.0   
35601               0.51                             1.0               0.0   
23256               0.39                             1.0               0.0   
27972               4.73                             1.0              32.0   

                                  Formula  
2860   <function <lambda> at 0x11d59ad40>  
32810  <function <lambda> at 0x11d59ad40>  
35601  <function <lambda> at 0x11d59ad40>  
23256  <function <lambda> at 0x11d59ad40>  
27972  <function <lambda> at 0x11d59ad40>

**5.	En un nuevo *Dataframe* mostrar por municipio: el número de habitaciones tipo individual, casa o departamento entero y compartido; también mostrar en otra columna el precio promedio de todas las habitaciones por municipio.**

In [69]:
df2=df.groupby(["municipio","room_type"]).count().iloc[:,0:1]
df3=df.groupby(["municipio","room_type"]).mean().iloc[:,4:5]
df4=pd.merge(df2,df3,on=["municipio","room_type"])
df4.rename(columns={'id': 'Num de instancias', 'price': 'precio_promedio'}, inplace=True)
df4

Num de instancias  precio_promedio
municipio     room_type                                          
Bronx         Entire home/apt                379       127.506596
              Private room                   652        66.890937
              Shared room                     60        59.800000
Brooklyn      Entire home/apt               9559       178.346202
              Private room                 10132        76.545428
              Shared room                    413        50.773723
Manhattan     Entire home/apt              13199       249.257994
              Private room                  7982       116.776622
              Shared room                    480        88.977083
Queens        Entire home/apt               2096       147.050573
              Private room                  3372        71.762456
              Shared room                    198        69.020202
Staten Island Entire home/apt                176       173.846591
              Private room                   188        62.292553
              Shared room                      9        57.444444

**6.	Crear una nueva columna con el rating de acuerdo a la siguiente formula, donde las variables son: puntaje del municipio, número de reviews y disponibilidad de la habitación al año.**

**Formula: Rating = (Puntaje de ciudad) + (número de review/ 629) + (disponibilidad / 365).**

El puntaje para cada ciudad es el siguiente {"Manhattan":10/10,"Brooklyn":8/10,"Queens":6/10,"Staten Island":4/10,"Bronx":2/10}.

In [70]:
def rating(x,y,z):
    puntuaje={"Manhattan":10/10,"Brooklyn":8/10,"Queens":6/10,"Staten Island":4/10,"Bronx":2/10}
    a=puntuaje[x]
    return a + y/629 + z/365
    

In [71]:
df["rating"]=df.apply(lambda x: rating(x["municipio"],x["number_of_reviews"],x["availability_365"]),axis=1)

In [ ]:
df

In [72]:
df.head()

id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787   
1  2595                             Skylit Midtown Castle     2845   
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632   
3  3831                   Cozy Entire Floor of Brownstone     4869   
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192   

     host_name  municipio        barrio  latitude  longitude        room_type  \
0         John   Brooklyn    Kensington  40.64749  -73.97237     Private room   
1     Jennifer  Manhattan       Midtown  40.75362  -73.98377  Entire home/apt   
2    Elisabeth  Manhattan        Harlem  40.80902  -73.94190     Private room   
3  LisaRoxanne   Brooklyn  Clinton Hill  40.68514  -73.95976  Entire home/apt   
4        Laura  Manhattan   East Harlem  40.79851  -73.94399  Entire home/apt   

   price  minimum_nights  number_of_reviews last_review  reviews_per_month  \
0  149.0             1.0                9.0  2018-10-19               0.21   
1  225.0             1.0               45.0  2019-05-21               0.38   
2  150.0             3.0                0.0         NaT                NaN   
3   89.0             1.0              270.0  2019-07-05               4.64   
4   80.0            10.0                9.0  2018-11-19               0.10   

   calculated_host_listings_count  availability_365  \
0                             6.0             365.0   
1                             2.0             355.0   
2                             1.0             365.0   
3                             1.0             194.0   
4                             1.0               0.0   

                              Formula    rating  
0  <function <lambda> at 0x11d59ad40>  1.814308  
1  <function <lambda> at 0x11d59ad40>  2.044145  
2  <function <lambda> at 0x11d59ad40>  2.000000  
3  <function <lambda> at 0x11d59ad40>  1.760760  
4  <function <lambda> at 0x11d59ad40>  1.014308

**7. Encontrar las 5 habitaciones de cada municipio con mayor rating**

In [76]:
df[(df["room_type"]=="Private room")].sort_values("rating",ascending=False).head(5)

id                            name   host_id host_name  municipio  \
2030    903947  Beautiful Bedroom in Manhattan   4734398        Jj  Manhattan   
2015    891117    Private Bedroom in Manhattan   4734398        Jj  Manhattan   
2031    903972      Great Bedroom in Manhattan   4734398        Jj  Manhattan   
11759  9145202         Room near JFK Queen Bed  47621202      Dona     Queens   
195      51572     Prime Location in Manhattan    237329       Lee  Manhattan   

        barrio  latitude  longitude     room_type  price  minimum_nights  \
2030    Harlem  40.82124  -73.93838  Private room   49.0             1.0   
2015    Harlem  40.82264  -73.94041  Private room   49.0             1.0   
2031    Harlem  40.82085  -73.94025  Private room   49.0             1.0   
11759  Jamaica  40.66730  -73.76831  Private room   47.0             1.0   
195    Chelsea  40.74859  -73.99671  Private room  123.0             1.0   

       number_of_reviews last_review  reviews_per_month  \
2030               597.0  2019-06-23               7.72   
2015               594.0  2019-06-15               7.57   
2031               607.0  2019-06-21               7.75   
11759              629.0  2019-07-05              14.58   
195                375.0  2019-06-18               3.52   

       calculated_host_listings_count  availability_365  \
2030                              3.0             342.0   
2015                              3.0             339.0   
2031                              3.0             293.0   
11759                             2.0             333.0   
195                               1.0             328.0   

                                  Formula    rating  
2030   <function <lambda> at 0x11d59ad40>  2.886112  
2015   <function <lambda> at 0x11d59ad40>  2.873123  
2031   <function <lambda> at 0x11d59ad40>  2.767764  
11759  <function <lambda> at 0x11d59ad40>  2.512329  
195    <function <lambda> at 0x11d59ad40>  2.494815

**8. Crear un dataframe con la cantidad de reviews de cada municipio de acuerdo a tipo de habitación**

In [50]:
df.groupby(["municipio","room_type"]).sum().iloc[:,6:7]

number_of_reviews
municipio     room_type                         
Bronx         Entire home/apt            11627.0
              Private room               16312.0
              Shared room                  432.0
Brooklyn      Entire home/apt           267128.0
              Private room              213653.0
              Shared room                 5793.0
Manhattan     Entire home/apt           235147.0
              Private room              209150.0
              Shared room                10272.0
Queens        Entire home/apt            60644.0
              Private room               93561.0
              Shared room                 2745.0
Staten Island Entire home/apt             5857.0
              Private room                5670.0
              Shared room                   14.0

**9. Encontrar los 10 barrios con mayor precio por habitación individual**

In [57]:
df[df["room_type"]=="Private room"].sort_values("price",ascending=False).head(10)["barrio"]

9151                Astoria
12342       Lower East Side
45666         East Flatbush
37194       Upper West Side
4345     Bedford-Stuyvesant
43670    Bedford-Stuyvesant
28946               Chelsea
39846    Financial District
946         Upper West Side
28727        Brighton Beach
Name: barrio, dtype: object

**10. Encontrar los 2 barrios con el menor precio por "dep/casa completo" que cumplan con el mejor rating de cada municipio**

In [82]:
df2=df[df["room_type"]=="Entire home/apt"].sort_values("price",ascending=True)
df2[df2["price"]==10].sort_values("rating",ascending=False).head(2)




id                                           name    host_id  \
33225  26235873                         Voted #1 Airbnb In NYC  197169969   
2860    1620248  Large furnished 2 bedrooms- - 30 days Minimum    2196224   

      host_name  municipio        barrio  latitude  longitude  \
33225     Maria     Queens       Jamaica  40.68939  -73.79886   
2860      Sally  Manhattan  East Village  40.73051  -73.98140   

             room_type  price  minimum_nights  number_of_reviews last_review  \
33225  Entire home/apt   10.0             2.0               22.0  2019-07-06   
2860   Entire home/apt   10.0            30.0                0.0         NaT   

       reviews_per_month  calculated_host_listings_count  availability_365  \
33225               1.76                             1.0             332.0   
2860                 NaN                             4.0             137.0   

                                  Formula    rating  
33225  <function <lambda> at 0x11d59ad40>  1.544565  
2860   <function <lambda> at 0x11d59ad40>  1.375342